name: 'retailanalytics'
version: '1.0.0'
config-version: 2

profile: 'retailanalytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  retailanalytics:
    staging:
      +materialized: view

    intermediate:
      +schema: intermediate
      +materialized: table

    marts:
      +schema: analytics
      +materialized: table